# -*- coding: utf-8 -*-
"""IDP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SKpTp1UvYa6B4veG5iWHOXKA8NeeLxI7
"""

import numpy as np
import soundfile as sf
from scipy import signal
import matplotlib.pyplot as plt
#If using termux
import subprocess
import shlex
#end if

def H(z,num,den):
    Num = np.polyval(num,pow(z,-1))
    Den = np.polyval(den,pow(z,-1))
    return Num/Den

x,fs = sf.read('Sound_Noise.wav')
sample_frequency = fs
order = 4
cutoff_freq = 4000.0
Wn = 2*cutoff_frequency/sample_frequency

b,a = signal.butter(order,Wn,'low')

omega = np.linspace(-np.pi,np.pi,len(x),endpoint=True)
z = np.exp(1j * omega)
H = H(z,b,a)
#subplots
plt.plot(omega,abs(H))
plt.xlabel('$w$')
plt.ylabel('$H(jw)$')
plt.grid()# minor

#If using termux
plt.savefig('../Figures/H(jw).pdf')
plt.savefig('../Figures/H(jw).eps')
subprocess.run(shlex.split("termux-open ../Figures/H(jw).pdf"))

#else
#plt.show()

from google.colab import drive
drive.mount('/content/drive')