# -*- coding: utf-8 -*-
"""IDP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SKpTp1UvYa6B4veG5iWHOXKA8NeeLxI7
"""

import numpy as np
import soundfile as sf
from scipy import signal
import matplotlib.pyplot as plt
from matplotlib.markers import MarkerStyle
from matplotlib import patches
#If using termux
import subprocess
import shlex
#end if
poles = [0.69382+1j*0.41,0.69382-1j*0.41,0.56617835+1j*0.134423,0.56617835-1j*0.134423]
p_real = [x.real for x in poles]
p_imag = [x.imag for x in poles]

x = np.linspace(-2,2,100)
ax = plt.subplot(111)
# Add unit circle and zero axes    
ax.add_patch(patches.Circle((0,0), radius=1, fill=False,color='black', ls='dashed'))

y1 = np.sqrt(16-x**2)
y2 = -np.sqrt(16-x**2)
plt.fill_between(x, y1, y2)

# Add circle passing through max abs(poles) and zero axes    
ax.add_patch(patches.Circle((0,0), radius=np.max(np.abs(poles)), fill=True,color='white',ls='solid'))
ax.add_patch(patches.Circle((0,0), radius=np.max(np.abs(poles)), fill=False,color='black',ls='solid'))

plt.plot(p_real,p_imag,'x',color='red')
plt.text(-0.1,0,"z=0")
plt.text(0.3,0.75,"ROC")
plt.text(0,1.1,"|z|=1")

plt.xlabel('real')
plt.ylabel('Imaginary')
plt.grid()
plt.axis('scaled')
plt.axis([-1.5,1.5,-1.5,1.5])

#If using termux
plt.savefig('../Figures/ROC.pdf')
plt.savefig('../Figures/ROC.eps')
subprocess.run(shlex.split("termux-open ../Figures/ROC.pdf"))

#else
#plt.show()

from google.colab import drive
drive.mount('/content/drive')